config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :scores
  resources :schedules, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :deliveries, :defaults => { :format => :json }
  resources :addresses, :defaults => { :format => :json }
  resources :delivery_requests, :defaults => { :format => :json }
  resources :ratings, :defaults => { :format => :json }
  resources :wallets, :defaults => { :format => :json }
  resources :notifications, :defaults => { :format => :json }
  resources :shops, :defaults => { :format => :json }
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  post '/users/sign_in' => 'sessions#create'

  get 'orders' => 'deliveries#orders', :defaults => { :format => :json }
  post '/deliveries/:id/finalize' => 'deliveries#finalize', :defaults => { :format => :json }
  post '/deliveries/:id/confirm' => 'deliveries#confirm', :defaults => { :format => :json }
  post '/deliveries/:id/cancel' => 'deliveries#cancel', :defaults => { :format => :json }
  post '/availabilities/:id/cancel' => 'availabilities#cancel', :defaults => { :format => :json }
  
  post '/delivery_requests/:id/cancel' => 'delivery_requests#cancel', :defaults => { :format => :json }
  post '/delivery_requests/saveProducts/:id' => 'delivery_requests#saveProducts', :defaults => { :format => :json }
  post '/delivery_requests/fetchProducts/:id' => 'delivery_requests#fetchProducts', :defaults => { :format => :json }
  post '/delivery_requests/calculateCommission' => 'delivery_requests#calculate_commission', :defaults => { :format => :json }
  
  get 'products' => 'shops#products', :defaults => { :format => :json }
  get '/wallets/:id/value' => 'wallets#value', :defaults => { :format => :json }

  get 'app' => 'home#app', :defaults => { :format => :html }

  root 'home#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base

	belongs_to :user

	after_create :send_notification

	private

	# Envoie un sms après la création de la notification si elle est de type sms.
	#
	# @!method send_notification
	# @!scope class
	# @!visibility public
	def send_notification

	    if self.sender == 'email'
	    	ap 'Send email'
	    elsif self.sender == 'push'
	    	ap 'Send push'
	    elsif self.sender == 'sms' || self.sender == 'onlysms'
				ap "Send sms to #{self.user.phone}"
        sms = "#{self.title}\nRendez-vous sur l'appli: http://goo.gl/VPv3ZH\nShopmycourses."
				phone = PhonyRails.normalize_number(self.user.phone, country_code: 'FR')
				
				if ENV['RACK_ENV'] != 'development' then
					result = HTTParty.post(ENV['OCTOPUSH_URL'], body: {
						user_login: ENV['OCTOPUSH_LOGIN'],
						api_key: ENV['OCTOPUSH_KEY'],
						sms_recipients: phone,
						sms_text: sms,
						sms_type: ENV['OCTOPUSH_TYPE'],
						sms_sender: 'SMC App',
						transactional: 1
					})
					ap "OCTOPUSH RESULT :"
					ap result
				else
					ap "SMS SKIP #{phone} Text: #{sms}"
				end
			end
	end

end

app/controllers/notifications_controller.rb
require 'json'

class NotificationsController < BaseController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # Retourne la liste de toutes les notifications correspondantes à l'utilisateur actuel.
  #
  # @note GET /notifications
  # @note GET /notifications.json
  def index
    @notifications = Notification.where(user_id: current_user.id, read: false, sender: ['push', 'sms'])
    
    
    #TESTING: return notifications with read:true of type delivery_request when the delivery_request has not related delivery.
    #@notifications_delivery_request_without_delivery = Notification.where(user_id: current_user.id, read: true, mode: "delivery_request", sender: ['push', 'sms']).select {|notification|
    #  meta = JSON.parse(notification.meta)
    #  delivery_request_id = meta['delivery_request']['id']
      #logger.debug "META #{meta['delivery_request']['id']}"
    #  !Delivery.any? {|delivery| delivery.delivery_request_id = delivery_request_id}
    #}
    #@notifications.concat @notifications_delivery_request_without_delivery
    
  end

  # Retourne la notification correspondant au paramètre 1.
  #
  # @note GET /notifications/1
  # @note GET /notifications/1.json
  def show
  end

  # Affiche le formulaire de création d'une nouvelle notification.
  #
  # @note GET /notifications/new
  def new
    @notification = Notification.new
  end


  # Affiche le formulaire d'édition de la notification correspondant au paramètre 1.
  #
  # @note GET /notifications/1/edit
  def edit
  end

  # Créée une nouvelle notification.
  #
  # @note POST /notifications
  # @note POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # Mise à jour de la notification correspondant au paramètre 1.
  #
  # @note PATCH/PUT /notifications/1
  # @note PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # Suppression de la notification correspondant au paramètre 1.
  #
  # @note DELETE /notifications/1
  # @note DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:mode, :title, :content, :sender, :user_id, :meta, :read)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sender %><br>
    <%= f.text_field :sender %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :meta %><br>
    <%= f.text_field :meta %>
  </div>
  <div class="field">
    <%= f.label :read %><br>
    <%= f.check_box :read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Title</th>
      <th>Content</th>
      <th>Sender</th>
      <th>User</th>
      <th>Meta</th>
      <th>Read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.type %></td>
        <td><%= notification.title %></td>
        <td><%= notification.content %></td>
        <td><%= notification.sender %></td>
        <td><%= notification.user_id %></td>
        <td><%= notification.meta %></td>
        <td><%= notification.read %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @notification.type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @notification.sender %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @notification.meta %>
</p>

<p>
  <strong>Read:</strong>
  <%= @notification.read %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>