config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :scores
  resources :schedules, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :deliveries, :defaults => { :format => :json }
  resources :addresses, :defaults => { :format => :json }
  resources :delivery_requests, :defaults => { :format => :json }
  resources :ratings, :defaults => { :format => :json }
  resources :wallets, :defaults => { :format => :json }
  resources :notifications, :defaults => { :format => :json }
  resources :shops, :defaults => { :format => :json }
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  post '/users/sign_in' => 'sessions#create'

  get 'orders' => 'deliveries#orders', :defaults => { :format => :json }
  post '/deliveries/:id/finalize' => 'deliveries#finalize', :defaults => { :format => :json }
  post '/deliveries/:id/confirm' => 'deliveries#confirm', :defaults => { :format => :json }
  post '/deliveries/:id/cancel' => 'deliveries#cancel', :defaults => { :format => :json }
  post '/availabilities/:id/cancel' => 'availabilities#cancel', :defaults => { :format => :json }
  
  post '/delivery_requests/:id/cancel' => 'delivery_requests#cancel', :defaults => { :format => :json }
  post '/delivery_requests/saveProducts/:id' => 'delivery_requests#saveProducts', :defaults => { :format => :json }
  post '/delivery_requests/fetchProducts/:id' => 'delivery_requests#fetchProducts', :defaults => { :format => :json }
  post '/delivery_requests/calculateCommission' => 'delivery_requests#calculate_commission', :defaults => { :format => :json }
  
  get 'products' => 'shops#products', :defaults => { :format => :json }
  get '/wallets/:id/value' => 'wallets#value', :defaults => { :format => :json }

  get 'app' => 'home#app', :defaults => { :format => :html }

  root 'home#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

	attr_accessor :was_created

	has_many :availabilities

	# Vérifie si l'horaire est expiré.
	#
	# @!method expired?
	def expired?
		if self.date.to_date < Date.today
			ap "date < today"
			return true
		elsif self.date.to_date == Date.today
			ap "date == today"
			expire_time = Time.parse("#{self.schedule[-3..-2]}:00")
			return expire_time < Time.now
		else
			ap "date > today"
			return false
		end
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < BaseController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # Retourne la liste de tous les créneaux.
  #
  # @note GET /schedules
  # @note GET /schedules.json
  def index
    @schedules = Schedule.all
  end


  # Retourne le créneau correspondant au paramètre 1.
  #
  # @note GET /schedules/1
  # @note GET /schedules/1.json
  def show
  end

  # Affiche le formulaire de création d'un nouveau créneau.
  #
  # @note GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # Affiche le formulaire d'édition d'un créneau correspondant au paramètre 1.
  #
  # @note GET /schedules/1/edit
  def edit
  end

  # Créée un nouveau créneau.
  #
  # @note POST /schedules
  # @note POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # Mise à jour du créneau correspondant au paramètre 1.
  #
  # @note PATCH/PUT /schedules/1
  # @note PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # Suppression du créneau correspondant au paramètre 1.
  #
  # @note DELETE /ratings/1
  # @note DELETE /ratings/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:schedule, :date)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.text_field :schedule %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Schedule</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.schedule %></td>
        <td><%= schedule.date %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Schedule:</strong>
  <%= @schedule.schedule %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>