config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :scores
  resources :schedules, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :deliveries, :defaults => { :format => :json }
  resources :addresses, :defaults => { :format => :json }
  resources :delivery_requests, :defaults => { :format => :json }
  resources :ratings, :defaults => { :format => :json }
  resources :wallets, :defaults => { :format => :json }
  resources :notifications, :defaults => { :format => :json }
  resources :shops, :defaults => { :format => :json }
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  post '/users/sign_in' => 'sessions#create'

  get 'orders' => 'deliveries#orders', :defaults => { :format => :json }
  post '/deliveries/:id/finalize' => 'deliveries#finalize', :defaults => { :format => :json }
  post '/deliveries/:id/confirm' => 'deliveries#confirm', :defaults => { :format => :json }
  post '/deliveries/:id/cancel' => 'deliveries#cancel', :defaults => { :format => :json }
  post '/availabilities/:id/cancel' => 'availabilities#cancel', :defaults => { :format => :json }
  
  post '/delivery_requests/:id/cancel' => 'delivery_requests#cancel', :defaults => { :format => :json }
  post '/delivery_requests/saveProducts/:id' => 'delivery_requests#saveProducts', :defaults => { :format => :json }
  post '/delivery_requests/fetchProducts/:id' => 'delivery_requests#fetchProducts', :defaults => { :format => :json }
  post '/delivery_requests/calculateCommission' => 'delivery_requests#calculate_commission', :defaults => { :format => :json }
  
  get 'products' => 'shops#products', :defaults => { :format => :json }
  get '/wallets/:id/value' => 'wallets#value', :defaults => { :format => :json }

  get 'app' => 'home#app', :defaults => { :format => :html }

  root 'home#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base

	after_save :calculate_average
	before_create :check_duplicate

	has_one :user, class_name: 'User', foreign_key: 'from_user_id'
	has_one :delivery
	belongs_to :user, class_name: 'User', foreign_key: 'to_user_id'

	private

	# Calcule la note moyenne d'un utilisateur.
	#
	# @!method calculate_average
	# @!scope class
	# @!visibility public
	def calculate_average
		@user = User.find_by(id: to_user_id)
		rating_average = Rating.where(to_user_id: to_user_id).average(:rating)
		@user.update(rating_average: rating_average)
	end

	private

	# Vérifie si l'utilisateur a déjà été noté sur une commande.
	#
	# @!method check_duplicate
	# @!scope class
	# @!visibility public
	def check_duplicate
		@rating = Rating.find_by(delivery_id: delivery_id, from_user_id: from_user_id)
		if @rating
			return false
		end
		return true
	end

end

app/controllers/ratings_controller.rb
class RatingsController < BaseController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # Retourne la liste de toutes les notes.
  #
  # @note GET /ratings
  # @note GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # Retourne la note correspondant au paramètre 1.
  #
  # @note GET /ratings/1
  # @note GET /ratings/1.json
  def show
  end

  # Affiche le formulaire de création d'une nouvelle note.
  #
  # @note GET /ratings/new
  def new
    @rating = Rating.new
  end

  # Affiche le formulaire d'édition de la note correspondant au paramètre 1.
  #
  # @note GET /ratings/1/edit
  def edit
  end

  # Créée une nouvelle note.
  #
  # @note POST /ratings
  # @note POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # Mise à jour de la note correspondant au paramètre 1.
  #
  # @note PATCH/PUT /ratings/1
  # @note PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # Suppression de l'adresse correspondant au paramètre 1.
  #
  # @note DELETE /ratings/1
  # @note DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:to_user_id, :from_user_id, :rating)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to_user_id %><br>
    <%= f.number_field :to_user_id %>
  </div>
  <div class="field">
    <%= f.label :from_user_id %><br>
    <%= f.number_field :from_user_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>To user</th>
      <th>From user</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.to_user_id %></td>
        <td><%= rating.from_user_id %></td>
        <td><%= rating.type %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To user:</strong>
  <%= @rating.to_user_id %>
</p>

<p>
  <strong>From user:</strong>
  <%= @rating.from_user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @rating.type %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>