config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :scores
  resources :schedules, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :availabilities, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :delivery_contents, :defaults => { :format => :json }
  resources :deliveries, :defaults => { :format => :json }
  resources :addresses, :defaults => { :format => :json }
  resources :delivery_requests, :defaults => { :format => :json }
  resources :ratings, :defaults => { :format => :json }
  resources :wallets, :defaults => { :format => :json }
  resources :notifications, :defaults => { :format => :json }
  resources :shops, :defaults => { :format => :json }
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}

  post '/users/sign_in' => 'sessions#create'

  get 'orders' => 'deliveries#orders', :defaults => { :format => :json }
  post '/deliveries/:id/finalize' => 'deliveries#finalize', :defaults => { :format => :json }
  post '/deliveries/:id/confirm' => 'deliveries#confirm', :defaults => { :format => :json }
  post '/deliveries/:id/cancel' => 'deliveries#cancel', :defaults => { :format => :json }
  post '/availabilities/:id/cancel' => 'availabilities#cancel', :defaults => { :format => :json }
  
  post '/delivery_requests/:id/cancel' => 'delivery_requests#cancel', :defaults => { :format => :json }
  post '/delivery_requests/saveProducts/:id' => 'delivery_requests#saveProducts', :defaults => { :format => :json }
  post '/delivery_requests/fetchProducts/:id' => 'delivery_requests#fetchProducts', :defaults => { :format => :json }
  post '/delivery_requests/calculateCommission' => 'delivery_requests#calculate_commission', :defaults => { :format => :json }
  
  get 'products' => 'shops#products', :defaults => { :format => :json }
  get '/wallets/:id/value' => 'wallets#value', :defaults => { :format => :json }

  get 'app' => 'home#app', :defaults => { :format => :html }

  root 'home#index'

end

app/models/delivery_content.rb
class DeliveryContent < ActiveRecord::Base

	belongs_to :delivery
	belongs_to :delivery_request

end

app/controllers/delivery_contents_controller.rb
class DeliveryContentsController < BaseController
  before_action :set_delivery_content, only: [:show, :edit, :update, :destroy]

  # Retourne la liste de toutes les lignes de commande.
  #
  # @note GET /delivery_contents
  # @note GET /delivery_contents.json
  def index
    @delivery_contents = DeliveryContent.all
  end

  # Retourne la ligne de commande correspondant au paramètre 1.
  #
  # @note GET /delivery_contents/1
  # @note GET /delivery_contents/1.json
  def show
  end

  # Affiche le formulaire de création d'une nouvelle ligne de commande.
  #
  # @note GET /delivery_contents/new
  def new
    @delivery_content = DeliveryContent.new
  end

  # Affiche le formulaire d'édition d'une ligne de commande correspondant au paramètre 1.
  #
  # @note GET /delivery_contents/1/edit
  def edit
  end

  # Créée une nouvelle ligne de commande.
  #
  # @note POST /delivery_contents
  # @note POST /delivery_contents.json
  def create
    @delivery_content = DeliveryContent.new(delivery_content_params)

    respond_to do |format|
      if @delivery_content.save
        format.html { redirect_to @delivery_content, notice: 'Delivery content was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_content }
      else
        format.html { render :new }
        format.json { render json: @delivery_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # Mise à jour de la ligne de commande correspondant au paramètre 1.
  #
  # @note PATCH/PUT /delivery_contents/1
  # @note PATCH/PUT /delivery_contents/1.json
  def update
    respond_to do |format|
      if @delivery_content.update(delivery_content_params)
        format.html { redirect_to @delivery_content, notice: 'Delivery content was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_content }
      else
        format.html { render :edit }
        format.json { render json: @delivery_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # Suppression de la ligne de commande correspondant au paramètre 1.
  #
  # @note DELETE /delivery_contents/1
  # @note DELETE /delivery_contents/1.json
  def destroy
    @delivery_content.destroy
    respond_to do |format|
      format.html { redirect_to delivery_contents_url, notice: 'Delivery content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_content
      @delivery_content = DeliveryContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_content_params
      params.require(:delivery_content).permit(:id_delivery, :id_product, :quantity, :unit_price)
    end
end

app/helpers/delivery_contents_helper.rb
module DeliveryContentsHelper
end

app/views/delivery_contents/_form.html.erb
<%= form_for(@delivery_content) do |f| %>
  <% if @delivery_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery_content.errors.count, "error") %> prohibited this delivery_content from being saved:</h2>

      <ul>
      <% @delivery_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_delivery %><br>
    <%= f.number_field :id_delivery %>
  </div>
  <div class="field">
    <%= f.label :id_product %><br>
    <%= f.number_field :id_product %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.text_field :unit_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/delivery_contents/edit.html.erb
<h1>Editing Delivery Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_content %> |
<%= link_to 'Back', delivery_contents_path %>

app/views/delivery_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Delivery Contents</h1>

<table>
  <thead>
    <tr>
      <th>Id delivery</th>
      <th>Id product</th>
      <th>Quantity</th>
      <th>Unit price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_contents.each do |delivery_content| %>
      <tr>
        <td><%= delivery_content.id_delivery %></td>
        <td><%= delivery_content.id_product %></td>
        <td><%= delivery_content.quantity %></td>
        <td><%= delivery_content.unit_price %></td>
        <td><%= link_to 'Show', delivery_content %></td>
        <td><%= link_to 'Edit', edit_delivery_content_path(delivery_content) %></td>
        <td><%= link_to 'Destroy', delivery_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery content', new_delivery_content_path %>

app/views/delivery_contents/new.html.erb
<h1>New Delivery Content</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_contents_path %>

app/views/delivery_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id delivery:</strong>
  <%= @delivery_content.id_delivery %>
</p>

<p>
  <strong>Id product:</strong>
  <%= @delivery_content.id_product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @delivery_content.quantity %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @delivery_content.unit_price %>
</p>

<%= link_to 'Edit', edit_delivery_content_path(@delivery_content) %> |
<%= link_to 'Back', delivery_contents_path %>